---
- name: Add Jenkins repository key
  rpm_key:
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: Jenkins Official Repository
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgcheck: yes
    gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
    enabled: yes

- name: Install Jenkins
  package:
    name: jenkins
    state: present


